# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.define "centos-6" do |c|
        c.vm.box = "kohkimakimoto/centos-6"
        c.vm.hostname = "cofu-vm-centos-6"
        c.vm.synced_folder "../", "/home/vagrant/src/github.com/kohkimakimoto/cofu"
        c.vm.provision :shell, :inline => <<-EOT
            # install golang
            cd /tmp
            wget -q https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.6.2.linux-amd64.tar.gz
            sudo  sudo sh -c 'echo "# golang settings" >> /etc/profile'
            sudo  sudo sh -c 'echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile'
            sudo  sudo sh -c 'echo "export GOPATH=/home/vagrant" >> /etc/profile'
            source /etc/profile
        EOT

        c.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

    config.vm.define "centos-7" do |c|
        c.vm.box = "kohkimakimoto/centos-7"
        c.vm.hostname = "cofu-vm-centos-7"
        c.vm.synced_folder "../", "/home/vagrant/src/github.com/kohkimakimoto/cofu"
        c.vm.provision :shell, :inline => <<-EOT
            # install golang
            cd /tmp
            wget -q https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.6.2.linux-amd64.tar.gz
            sudo  sudo sh -c 'echo "# golang settings" >> /etc/profile'
            sudo  sudo sh -c 'echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile'
            sudo  sudo sh -c 'echo "export GOPATH=/home/vagrant" >> /etc/profile'
            source /etc/profile
        EOT

        c.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
    end

    config.vm.define "centos-7-demo" do |c|
        c.vm.box = "kohkimakimoto/centos-7"
        c.vm.hostname = "cofu-vm-centos-7"
        c.vm.synced_folder "../", "/home/vagrant/src/github.com/kohkimakimoto/cofu"
        c.vm.network :private_network, type: "dhcp"
        c.vm.provision :shell, :inline => <<-EOT
            # install golang
            cd /tmp
            wget -q https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.6.2.linux-amd64.tar.gz
            sudo  sudo sh -c 'echo "# golang settings" >> /etc/profile'
            sudo  sudo sh -c 'echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile'
            sudo  sudo sh -c 'echo "export GOPATH=/home/vagrant" >> /etc/profile'
            source /etc/profile
        EOT

        c.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
    end
end
